- name: pulling jenkins image
  docker_image:
    name: "{{ jenkins_container_name }}"

- name: running jenkins service
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - docker_service:
        project_src: jenkins
        state: absent
    - docker_service:
        project_name: jenkins
        definition:
          version: '2'
          services:
            jenkins: 
              image: "{{ jenkins_container_image}}"  
  



