- name: pulling jenkins image
  docker_image:
    name: {{ jenkins_container_name }}

- name: running jenkins service
  docker_container:
    name: {{ jenkins_container_name }}
    image: {{ jenkins_container_image }}



